// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohulgfuqsnlriwqepznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odWxnZnVxc25scml3cWVwem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwMTgzNjgsImV4cCI6MjA4MDU5NDM2OH0.28h4nokhY9Qy1tDEP8IsiS6uJN9djtDjV2fucCKhc7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});